#!/bin/sh

# Force linear modifiers
export WPEBACKEND_FDO_FORCE_DMABUF_LINEAR_MODIFIERS=1

# Ignore X-Frame-Origin
export WEBKIT_IGNORE_X_FRAME_ORIGIN=1

# Platform parameter
PLATFORM="-P drm"

# WebSettings parameter
WEBSETTINGS="-C /root/websettings.cfg"

# Whether there's a proxy on the http_proxy env var
if [ -z "${http_proxy}" ]; then
    PROXY=""
else
    PROXY="--proxy \"${http_proxy}\""
fi

# Whether there's a semicolon separated list of hosts to avoid proxy on the no_proxy env var.
# Example: "www.google.com;www.igalia.com;192.168.1.1"
# See https://webkitgtk.org/reference/webkit2gtk/stable/WebKitNetworkProxySettings.html#webkit-network-proxy-settings-new
if [ -z "${no_proxy}" ]; then
    NO_PROXY=""
else
    hosts=$(echo $no_proxy | tr ";" "\n")
    for i in $hosts; do
        NO_PROXY=$NO_PROXY" --ignore-host \"$i\""
    done
fi

# URL
if [ -n "$1" ]; then
    URL=$1
else
    URL="https://wpewebkit.org"
fi

cd /root && eval "cog --doc-viewer $PLATFORM $WEBSETTINGS $PROXY $NO_PROXY \"$URL\""
