#!/bin/sh

start() {
	echo -n "Starting WPE: "
	if [[ -z "${COG_URL}" ]]; then
		URL="http://www.igalia.com"
	else
		URL="${COG_URL}"
	fi
	if [ -n "$URL" ]; then
		/usr/bin/wpe --loop $URL &> /dev/null &
		echo "OK"
	else
		echo "NO URL"
	fi
}

stop() {
	echo -n "Stopping WPE: "
	killall wpe WPELauncher WPEWebProcess WPENetworkProcess &> /dev/null
	echo "OK"
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
	;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
